spring.application.name=cart-service
server.port=8086
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/prime_basket}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:vicky123}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update

#Eureka
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

#Zipkin
# Send every trace during local development
management.tracing.sampling.probability=1.0

# Zipkin collector endpoint
management.tracing.export.zipkin.endpoint=${ZIPKIN_ENDPOINT:http://localhost:9411/api/v2/spans}

# Optional: clearer trace/span IDs in logs
logging.pattern.correlation=[${spring.application.name:},%X{traceId:-},%X{spanId:-}]
logging.include-application-name=false

#Micrometer
spring.cloud.openfeign.micrometer.enabled=true
